[project]
name = "de-assignment-intelligencia-dlt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dlt[duckdb,postgres,workspace]>=1.18.0",
    "tqdm>=4.67.1",
]
