[load]
truncate_staging_dataset=true

[runtime]
log_level="WARNING"  # the system log level of dlt
log_format="JSON"
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry = true
