[destination.postgres.credentials]

database = "olsdb"
username = "vitalex"
password = "W1r3l3ssotm" # replace with your password
host = "localhost" # or the IP address location of your database
port = 5432
connect_timeout = 15
query.options = "-ctimezone=Europe/Paris"